name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set base for GitHub Pages
        run: |
          sed -i 's/"homepage": "\/"/"homepage": "\/yingjieweb\/"/g' package.json

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build

  build-and-deploy-io:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set base for GitHub Pages
        run: |
          sed -i 's/"homepage": "\/"/"homepage": "\/yingjieweb\/"/g' package.json

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_IO }}
          external_repository: yingjieweb/yingjieweb.github.io
          publish_branch: master
          publish_dir: ./build

